# Generated by Django 2.0.10 on 2019-02-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealapp', '0002_auto_20190131_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='neighbourhood',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
