# Generated by Django 2.0.10 on 2019-02-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealapp', '0003_restaurant_neighbourhood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_items',
            name='item_description',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='menu_items',
            name='item_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
