# Generated by Django 2.0.10 on 2019-03-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealapp', '0004_auto_20190218_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_items',
            name='cuisine',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
