# Generated by Django 2.1.5 on 2019-01-14 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=15)),
                ('item_name', models.CharField(default=None, max_length=15)),
                ('item_description', models.CharField(blank=True, default=None, max_length=500)),
                ('item_price', models.FloatField(default=None, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=15)),
                ('long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mealapp.Menu')),
            ],
        ),
    ]
