# Generated by Django 2.1.5 on 2019-01-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_items',
            name='item_name',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='menu_items',
            name='type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
