# Generated by Django 2.1.5 on 2019-01-18 10:07

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mealapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='preferences',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('vegan', 'Vegan'), ('halal', 'Halal')], max_length=11),
        ),
    ]
