# Generated by Django 2.0.10 on 2019-01-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='lat',
            field=models.DecimalField(decimal_places=9, max_digits=9),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='long',
            field=models.DecimalField(decimal_places=9, max_digits=9),
        ),
    ]
