# Generated by Django 2.0.10 on 2019-01-31 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='opening',
            field=models.TextField(default=None, null=True),
        ),
    ]
