# Generated by Django 2.1.5 on 2019-01-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealapp', '0002_auto_20190114_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='item_description',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='menu',
            name='item_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=3),
        ),
    ]
