# Generated by Django 2.1.5 on 2019-01-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealapp', '0002_auto_20190118_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='preferences',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
