# Generated by Django 2.0.10 on 2019-01-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealapp', '0003_auto_20190127_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=15),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='long',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=15),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='opening',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
