# Generated by Django 2.1.5 on 2019-01-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealapp', '0003_auto_20190115_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='item_price',
            field=models.FloatField(default=None, max_length=2),
        ),
        migrations.AlterField(
            model_name='menu',
            name='restaurant_name',
            field=models.CharField(max_length=15),
        ),
    ]
