# Generated by Django 2.0.10 on 2019-01-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealapp', '0004_auto_20190129_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='lat',
            field=models.DecimalField(decimal_places=9, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='long',
            field=models.DecimalField(decimal_places=9, max_digits=15, null=True),
        ),
    ]
