# Generated by Django 2.1.5 on 2019-01-22 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mealapp', '0004_auto_20190122_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='menu',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mealapp.Menu_Items'),
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
