# Generated by Django 2.0.10 on 2019-01-29 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mealapp', '0005_auto_20190129_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='menu_items',
        ),
        migrations.AlterField(
            model_name='menu_items',
            name='restaurant_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mealapp.Restaurant'),
        ),
    ]
