# Generated by Django 2.1.5 on 2019-01-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealapp', '0005_auto_20190122_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='menu',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='menu',
            field=models.ManyToManyField(blank=True, related_name='related_to', to='mealapp.Menu_Items'),
        ),
    ]
