# Generated by Django 2.0.10 on 2019-01-31 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealapp', '0006_auto_20190129_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
    ]
