# Generated by Django 2.1.5 on 2019-01-22 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealapp', '0006_auto_20190122_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='menu',
            new_name='menu_items',
        ),
    ]
