# Generated by Django 2.1.5 on 2019-01-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealapp', '0007_auto_20190122_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='long',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='close',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=2),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='opening',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=2),
        ),
    ]
