# Generated by Django 2.1.7 on 2019-03-25 14:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealapp', '0007_restaurant_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='menu_items',
            name='ingredients',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), default=list, size=None),
        ),
    ]
