# Generated by Django 2.1.5 on 2019-01-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealapp', '0008_auto_20190122_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='close',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='opening',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
